services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger

    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

    command:
      - "--collector.otlp.http.cors.allowed-origins=http://localhost:5173"
      - "--collector.otlp.http.cors.allowed-headers=Content-Type"
